/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fbla;

/**
 *
 * @author Tim
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form MoreInfo
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moreInfoName = new javax.swing.JLabel();
        moreInfoTypeLabel = new javax.swing.JLabel();
        moreInfoType = new javax.swing.JLabel();
        moreInfoResourcesLabel = new javax.swing.JLabel();
        moreInfoResources = new javax.swing.JLabel();
        helpBackBtn = new javax.swing.JButton();
        moreInfoType1 = new javax.swing.JLabel();
        moreInfoType2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moreInfoName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        moreInfoName.setText("Help");

        moreInfoTypeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moreInfoTypeLabel.setText("Search Menu");

        moreInfoType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        moreInfoType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        moreInfoType.setText("The search menu is where you will find the partners stored in the database. Click the labels on the table to sort by ascending or descending. Type in the search box to search for the");
        moreInfoType.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moreInfoType.setFocusTraversalPolicyProvider(true);
        moreInfoType.setFocusable(false);
        moreInfoType.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        moreInfoType.setMaximumSize(new java.awt.Dimension(1188, 17));

        moreInfoResourcesLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moreInfoResourcesLabel.setText("Input Menu");

        moreInfoResources.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        helpBackBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        helpBackBtn.setText("Back");
        helpBackBtn.setActionCommand("");
        helpBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBackBtnActionPerformed(evt);
            }
        });

        moreInfoType1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        moreInfoType1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        moreInfoType1.setText("partners you desire and filter out the rest. Click the refresh button to reload the interface. Please click the refresh button after inputting partners. Click the clear button to clear the database.");
        moreInfoType1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moreInfoType1.setFocusTraversalPolicyProvider(true);
        moreInfoType1.setFocusable(false);
        moreInfoType1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        moreInfoType1.setMaximumSize(new java.awt.Dimension(1188, 17));

        moreInfoType2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        moreInfoType2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        moreInfoType2.setText("Input the partner's information in the respective text box. Press submit to add them to the database and store them in a text file. You can import other files to import the partners.");
        moreInfoType2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moreInfoType2.setFocusTraversalPolicyProvider(true);
        moreInfoType2.setFocusable(false);
        moreInfoType2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        moreInfoType2.setMaximumSize(new java.awt.Dimension(1188, 17));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(moreInfoResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78))
                    .addComponent(moreInfoName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreInfoType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moreInfoResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moreInfoTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(moreInfoType1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpBackBtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moreInfoType2, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moreInfoName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moreInfoTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moreInfoType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreInfoType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247)
                .addComponent(moreInfoResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreInfoType2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreInfoResources, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(264, 264, 264)
                .addComponent(helpBackBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBackBtnActionPerformed
        // TODO add your handling code here:
        //Closes the window
        dispose();
    }//GEN-LAST:event_helpBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpBackBtn;
    private javax.swing.JLabel moreInfoName;
    private javax.swing.JLabel moreInfoResources;
    private javax.swing.JLabel moreInfoResourcesLabel;
    private javax.swing.JLabel moreInfoType;
    private javax.swing.JLabel moreInfoType1;
    private javax.swing.JLabel moreInfoType2;
    private javax.swing.JLabel moreInfoTypeLabel;
    // End of variables declaration//GEN-END:variables
}
